name: Ecommerce UI Automation Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r Ecommerce_UI_Automation_Framework/requirements.txt
        
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Ecommerce_UI_Automation_Framework" >> $GITHUB_ENV

    - name: Clean old logs
      run: |
        rm -rf Ecommerce_UI_Automation_Framework/logs/*
       
    - name: Run tests
      working-directory: Ecommerce_UI_Automation_Framework
      run: |
        pytest tests --html=reports/index.html --self-contained-html

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: Ecommerce_UI_Automation_Framework/reports/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Ecommerce_UI_Automation_Framework/reports
    - name: Upload screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
          name: failure-screenshots
          path: Ecommerce_UI_Automation_Framework/screenshots/    
          
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
           name: test-logs
           path: Ecommerce_UI_Automation_Framework/logs/
           
    - name: Commit logs 
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         
         git add Ecommerce_UI_Automation_Framework/logs/
         
         
         git commit -m "Update logs " || echo "No changes to commit"
         
         git push 
       
